In [1]:
# Load embeddings
from pickle import load
import numpy as np
from PIL import Image
import os

image_folder = "images/"

# Break into categories
clothing_images = [Image.open(os.path.join(image_folder, file)) for file in os.listdir(image_folder) if file.endswith("c.png")]
clothing_labels = [file.split("-")[0].split("_") for file in os.listdir(image_folder) if file.endswith("c.png")]
clothing_labels = [[lab[0], lab[1], lab[2][:-1]] if lab[2].endswith("s") else lab for lab in clothing_labels]

full_body_images = [Image.open(os.path.join(image_folder, file)) for file in os.listdir(image_folder) if file.endswith("fb.png")]
full_body_labels = [file.split("-")[0].split("_") for file in os.listdir(image_folder) if file.endswith("fb.png")]
full_body_filenames = [file for file in os.listdir(image_folder) if file.endswith("fb.png")]
full_body_labels = [[lab[0], lab[1], lab[2][:-1]] if lab[2].endswith("s") else lab for lab in full_body_labels]

In [2]:
# # Preprocess embedings
# clothing_genders = np.zeros((clothing_embed.shape[0], 2))
# clothing_genders[np.array([{"mens": 0, "womens": 1}[lab[1]] for lab in clothing_labels])] = 1

# clothing_type = np.zeros((clothing_embed.shape[0], 6))
# clothing_type[np.array([
#     {"shirt": 0, "top": 1, "sweater": 2, "pant": 3, "skirt": 4, "short": 5}[lab[2]]
#     for lab in clothing_labels
# ])] = 1

In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

import tensorflow as tf

tf.config.list_physical_devices()

2024-04-30 20:42:06.143533: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-30 20:42:06.187976: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-30 20:42:06.798519: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [4]:
# Train model
import tensorflow as tf

class triplet_model(tf.keras.Model):
    def __init__(self, model, output_size, margin=0, trainable=True,):
        super().__init__(trainable=trainable)
        self.clothing_model = tf.keras.models.Sequential([
            model,
            tf.keras.layers.Dense(output_size * 4, activation="elu"),
            tf.keras.layers.Dense(output_size * 4, activation="elu"),
            tf.keras.layers.Dense(output_size, activation="sigmoid"),
        ])
        self.outfit_model = tf.keras.models.Sequential([
            model,
            tf.keras.layers.Dense(output_size * 4, activation="elu"),
            tf.keras.layers.Dense(output_size * 4, activation="elu"),
            tf.keras.layers.Dense(output_size, activation="sigmoid"),
        ])
        self.margin = margin

    def compile(self, **kwargs):
        self.clothing_model.compile(**kwargs)
        self.outfit_model.compile(**kwargs)
        super().compile(**kwargs)

    # https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#supporting_sample_weight_class_weight
    # https://en.wikipedia.org/wiki/Triplet_loss
    def train_step(self, data):
        x, x_positive, x_negative = data

        with tf.GradientTape() as tape:
            y_anchor = self.clothing_model(x)
            y_positive = self.outfit_model(x_positive)
            y_negative = self.outfit_model(x_negative)
            
            dist_positive = tf.math.sqrt(tf.math.reduce_sum(tf.math.square(y_anchor - y_positive), axis=-1))
            dist_negative = tf.math.sqrt(tf.math.reduce_sum(tf.math.square(y_anchor - y_negative), axis=-1))
            loss = tf.math.maximum(dist_positive - dist_negative + self.margin, 0)
            loss = tf.math.reduce_sum(loss)

        # Compute gradients
        trainable_vars = self.clothing_model.trainable_variables + self.outfit_model.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)

        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        # Update the metrics.
        # Metrics are configured in `compile()`.
        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(tf.ones((tf.shape(x)[0], 1)), tf.expand_dims(tf.cast(dist_positive < dist_negative, float), axis=-1))

        # Return a dict mapping metric names to current value.
        # Note that it will include the loss (tracked in self.metrics).
        return {m.name: m.result() for m in self.metrics}

    def test_step(self, data):
        x, x_positive, x_negative = data
        
        y_anchor = self.clothing_model(x)
        y_positive = self.outfit_model(x_positive)
        y_negative = self.outfit_model(x_negative)
        
        dist_positive = tf.math.sqrt(tf.math.reduce_sum(tf.math.square(y_anchor - y_positive), axis=-1))
        dist_negative = tf.math.sqrt(tf.math.reduce_sum(tf.math.square(y_anchor - y_negative), axis=-1))
        loss = tf.math.maximum(dist_positive - dist_negative + self.margin, 0)
        loss = tf.math.reduce_sum(loss)

        # Update the metrics.
        # Metrics are configured in `compile()`.
        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(tf.ones((tf.shape(x)[0], 1)), tf.expand_dims(tf.cast(dist_positive < dist_negative, float), axis=-1))

        # Return a dict mapping metric names to current value.
        # Note that it will include the loss (tracked in self.metrics).
        return {m.name: m.result() for m in self.metrics}


def triplet_sample_generator(validation=False):
    if validation:
        inds = np.arange(len(clothing_images))[np.arange(len(clothing_images)) % 10 == 0]
    else:
        inds = np.arange(len(clothing_images))[np.arange(len(clothing_images)) % 10 != 0]

    for i in inds:
        neg_inds = inds[inds != i]
        np.random.shuffle(neg_inds)

        anchor = tf.keras.applications.mobilenet_v3.preprocess_input(np.array(clothing_images[i].resize((224, 224))))
        positive = tf.keras.applications.mobilenet_v3.preprocess_input(np.array(full_body_images[i].resize((224, 224))))
        negative = tf.keras.applications.mobilenet_v3.preprocess_input(np.array(full_body_images[neg_inds[0]].resize((224, 224))))
        
        yield anchor, positive, negative

img_spec = tf.TensorSpec((224, 224, 3), float)
ds_train = tf.data.Dataset.from_generator(triplet_sample_generator, output_signature=(img_spec, img_spec, img_spec))
ds_valid = tf.data.Dataset.from_generator(lambda: triplet_sample_generator(validation=True), output_signature=(img_spec, img_spec, img_spec))

model = tf.keras.applications.MobileNetV3Large(
    include_top=False,
    weights='imagenet',
    input_tensor=None,
    input_shape=(224, 224, 3),
    pooling="avg"
)
inp = tf.keras.Input((224, 224, 3))
model = tf.keras.Model(inputs=inp, outputs=model(inp))
model.summary()

model = triplet_model(
    model,
    512,
    margin = 1
)

model.compile(
    optimizer="adam",
    run_eagerly=False,
    metrics=["binary_crossentropy", "binary_accuracy"]
)

model.fit(
    ds_train.batch(32),
    epochs=100,
    validation_data=ds_valid.batch(32),
    callbacks=[tf.keras.callbacks.EarlyStopping(monitor="val_binary_accuracy", patience=25, restore_best_weights=True)],
)   

2024-04-30 20:42:07.757342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22253 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:18:00.0, compute capability: 8.9
2024-04-30 20:42:07.757840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 22446 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:af:00.0, compute capability: 8.6


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ MobilenetV3large (Functional)   │ (None, 960)            │     2,996,352 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,996,352 (11.43 MB)

 Trainable params: 2,971,952 (11.34 MB)

 Non-trainable params: 24,400 (95.31 KB)

Epoch 1/100


I0000 00:00:1714524160.718807   20768 service.cc:145] XLA service 0x7cfaac005600 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1714524160.718875   20768 service.cc:153]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9
I0000 00:00:1714524160.718884   20768 service.cc:153]   StreamExecutor device (1): NVIDIA GeForce RTX 3090, Compute Capability 8.6
2024-04-30 20:42:42.052412: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-04-30 20:42:46.254011: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8907
I0000 00:00:1714524168.723857   20982 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_32451', 24 bytes spill stores, 24 bytes spill loads

I0000 00:00:1714524168.774793   20997 asm_compiler.cc:369] ptxas warning

     17/Unknown 83s 1s/step - binary_accuracy: 0.4003 - binary_crossentropy: 9.6657 - loss: 32.2482

I0000 00:00:1714524219.797970   21254 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_32451', 40 bytes spill stores, 40 bytes spill loads

I0000 00:00:1714524219.849889   21259 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_32451', 24 bytes spill stores, 24 bytes spill loads

I0000 00:00:1714524219.942013   21241 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_32451', 32 bytes spill stores, 32 bytes spill loads

I0000 00:00:1714524219.949384   21262 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_32451', 40 bytes spill stores, 40 bytes spill loads

I0000 00:00:1714524219.969955   21244 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_12670', 248 bytes spill stores, 248 bytes spill loads

I0000 00:00:1714524219.

     18/Unknown 115s 3s/step - binary_accuracy: 0.3957 - binary_crossentropy: 9.7401 - loss: 32.1943

2024-04-30 20:44:03.468171: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:44:03.471978: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]
/home/ian/miniconda3/envs/tf/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)
I0000 00:00:1714524253.076596   21642 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_2360', 248 bytes spill stores, 248 bytes spill loads

2024-04-30 20:44:16.530325: W tensorflow/core/framework/local_rendezvous

18/18 ━━━━━━━━━━━━━━━━━━━━ 128s 4s/step - binary_accuracy: 0.3916 - binary_crossentropy: 9.8066 - loss: 32.1461 - val_binary_accuracy: 0.0000e+00 - val_binary_crossentropy: 16.1181 - val_loss: 31.5000
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 774ms/step - binary_accuracy: 0.0328 - binary_crossentropy: 15.5895 - loss: 31.9647

2024-04-30 20:44:30.864025: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:44:30.865430: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 889ms/step - binary_accuracy: 0.0335 - binary_crossentropy: 15.5780 - loss: 31.9231 - val_binary_accuracy: 0.0476 - val_binary_crossentropy: 15.3506 - val_loss: 31.5000
Epoch 3/100


2024-04-30 20:44:32.637065: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:44:32.637193: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 824ms/step - binary_accuracy: 0.0475 - binary_crossentropy: 15.3518 - loss: 31.9248

2024-04-30 20:44:47.757499: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:44:47.758958: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 931ms/step - binary_accuracy: 0.0471 - binary_crossentropy: 15.3589 - loss: 31.8842 - val_binary_accuracy: 0.0000e+00 - val_binary_crossentropy: 16.1181 - val_loss: 31.5000
Epoch 4/100


2024-04-30 20:44:49.537436: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:44:49.537521: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 838ms/step - binary_accuracy: 0.0698 - binary_crossentropy: 14.9928 - loss: 31.8883

2024-04-30 20:45:04.739699: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:04.741371: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 946ms/step - binary_accuracy: 0.0688 - binary_crossentropy: 15.0096 - loss: 31.8496 - val_binary_accuracy: 0.0476 - val_binary_crossentropy: 15.3506 - val_loss: 31.5733
Epoch 5/100


2024-04-30 20:45:06.525325: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:06.525409: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:45:06.525458: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 804ms/step - binary_accuracy: 0.1941 - binary_crossentropy: 12.9902 - loss: 31.8845

2024-04-30 20:45:21.149317: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:21.154015: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 917ms/step - binary_accuracy: 0.1915 - binary_crossentropy: 13.0308 - loss: 31.8449 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5147
Epoch 6/100


2024-04-30 20:45:22.904595: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:22.904675: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:45:22.904703: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 740ms/step - binary_accuracy: 0.0795 - binary_crossentropy: 14.8373 - loss: 31.9401

2024-04-30 20:45:36.539561: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:36.540951: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 15s 846ms/step - binary_accuracy: 0.0798 - binary_crossentropy: 14.8321 - loss: 31.8983 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5586
Epoch 7/100


2024-04-30 20:45:38.297327: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:38.297410: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:45:38.297439: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 790ms/step - binary_accuracy: 0.0713 - binary_crossentropy: 14.9685 - loss: 31.9759

2024-04-30 20:45:52.698570: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:52.700181: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 895ms/step - binary_accuracy: 0.0719 - binary_crossentropy: 14.9594 - loss: 31.9338 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4853
Epoch 8/100


2024-04-30 20:45:54.442737: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:45:54.442819: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:45:54.442849: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 845ms/step - binary_accuracy: 0.0794 - binary_crossentropy: 14.8386 - loss: 31.9596

2024-04-30 20:46:09.777657: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:09.779081: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 951ms/step - binary_accuracy: 0.0797 - binary_crossentropy: 14.8334 - loss: 31.9185 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.5293
Epoch 9/100


2024-04-30 20:46:11.529449: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:11.529530: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:46:11.529560: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 820ms/step - binary_accuracy: 0.0804 - binary_crossentropy: 14.8226 - loss: 31.9678

2024-04-30 20:46:26.442569: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:26.443854: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 927ms/step - binary_accuracy: 0.0806 - binary_crossentropy: 14.8182 - loss: 31.9258 - val_binary_accuracy: 0.0635 - val_binary_crossentropy: 15.0947 - val_loss: 31.5000
Epoch 10/100


2024-04-30 20:46:28.218196: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:28.218277: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:46:28.218307: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 791ms/step - binary_accuracy: 0.0760 - binary_crossentropy: 14.8931 - loss: 31.9855

2024-04-30 20:46:42.604869: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:42.606450: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 896ms/step - binary_accuracy: 0.0764 - binary_crossentropy: 14.8865 - loss: 31.9433 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.5293
Epoch 11/100


2024-04-30 20:46:44.343742: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:44.343813: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:46:44.343843: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 796ms/step - binary_accuracy: 0.0728 - binary_crossentropy: 14.9439 - loss: 31.9565

2024-04-30 20:46:58.803367: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:46:58.804952: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 903ms/step - binary_accuracy: 0.0732 - binary_crossentropy: 14.9377 - loss: 31.9151 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4413
Epoch 12/100


2024-04-30 20:47:00.582767: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:00.582847: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:47:00.582880: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 777ms/step - binary_accuracy: 0.0783 - binary_crossentropy: 14.8561 - loss: 31.9588

2024-04-30 20:47:14.771503: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:14.772936: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 861ms/step - binary_accuracy: 0.0787 - binary_crossentropy: 14.8499 - loss: 31.9174 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4707
Epoch 13/100


2024-04-30 20:47:16.163825: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:16.163899: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:47:16.163929: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 844ms/step - binary_accuracy: 0.0764 - binary_crossentropy: 14.8863 - loss: 31.9548

2024-04-30 20:47:31.430058: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:31.431600: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 949ms/step - binary_accuracy: 0.0767 - binary_crossentropy: 14.8816 - loss: 31.9132 - val_binary_accuracy: 0.0635 - val_binary_crossentropy: 15.0947 - val_loss: 31.5733
Epoch 14/100


2024-04-30 20:47:33.173456: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:33.173533: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:47:33.173564: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 776ms/step - binary_accuracy: 0.0760 - binary_crossentropy: 14.8927 - loss: 31.9748

2024-04-30 20:47:47.353342: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:47.354674: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 882ms/step - binary_accuracy: 0.0763 - binary_crossentropy: 14.8876 - loss: 31.9322 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.4854
Epoch 15/100


2024-04-30 20:47:49.105229: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:47:49.105317: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 820ms/step - binary_accuracy: 0.0775 - binary_crossentropy: 14.8694 - loss: 31.9619

2024-04-30 20:48:04.012232: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:04.013706: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 927ms/step - binary_accuracy: 0.0779 - binary_crossentropy: 14.8625 - loss: 31.9199 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4853
Epoch 16/100


2024-04-30 20:48:05.787662: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:05.787751: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:48:05.787781: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 775ms/step - binary_accuracy: 0.0665 - binary_crossentropy: 15.0466 - loss: 31.9560

2024-04-30 20:48:19.910664: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:19.912213: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 883ms/step - binary_accuracy: 0.0669 - binary_crossentropy: 15.0395 - loss: 31.9152 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5147
Epoch 17/100


2024-04-30 20:48:21.700656: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:21.700753: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 818ms/step - binary_accuracy: 0.0778 - binary_crossentropy: 14.8645 - loss: 31.9525

2024-04-30 20:48:36.635754: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:36.637136: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 903ms/step - binary_accuracy: 0.0784 - binary_crossentropy: 14.8548 - loss: 31.9112 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.4853
Epoch 18/100


2024-04-30 20:48:38.031144: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:38.031222: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:48:38.031251: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 796ms/step - binary_accuracy: 0.0780 - binary_crossentropy: 14.8606 - loss: 31.9513

2024-04-30 20:48:52.508620: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:52.510309: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 902ms/step - binary_accuracy: 0.0783 - binary_crossentropy: 14.8557 - loss: 31.9089 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.4707
Epoch 19/100


2024-04-30 20:48:54.265349: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:48:54.265439: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 817ms/step - binary_accuracy: 0.0751 - binary_crossentropy: 14.9075 - loss: 31.9524

2024-04-30 20:49:09.109803: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:09.111173: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 925ms/step - binary_accuracy: 0.0755 - binary_crossentropy: 14.9016 - loss: 31.9112 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4267
Epoch 20/100


2024-04-30 20:49:10.894080: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:10.894155: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:49:10.894184: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 804ms/step - binary_accuracy: 0.0691 - binary_crossentropy: 15.0044 - loss: 31.9515

2024-04-30 20:49:25.566649: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:25.568007: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 908ms/step - binary_accuracy: 0.0696 - binary_crossentropy: 14.9965 - loss: 31.9098 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4854
Epoch 21/100


2024-04-30 20:49:27.293551: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:27.293636: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 827ms/step - binary_accuracy: 0.0793 - binary_crossentropy: 14.8402 - loss: 31.9657

2024-04-30 20:49:42.274606: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:42.276107: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 933ms/step - binary_accuracy: 0.0796 - binary_crossentropy: 14.8348 - loss: 31.9234 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.5000
Epoch 22/100


2024-04-30 20:49:44.030878: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:44.030957: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:49:44.030986: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 822ms/step - binary_accuracy: 0.0801 - binary_crossentropy: 14.8271 - loss: 31.9610

2024-04-30 20:49:58.953116: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:49:58.954613: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 927ms/step - binary_accuracy: 0.0805 - binary_crossentropy: 14.8210 - loss: 31.9190 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5294
Epoch 23/100


2024-04-30 20:50:00.703606: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:00.703680: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 778ms/step - binary_accuracy: 0.0800 - binary_crossentropy: 14.8285 - loss: 31.9524

2024-04-30 20:50:14.847736: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:14.849123: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 884ms/step - binary_accuracy: 0.0805 - binary_crossentropy: 14.8208 - loss: 31.9099 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.4707
Epoch 24/100


2024-04-30 20:50:16.591989: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:16.592082: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:50:16.592112: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 799ms/step - binary_accuracy: 0.0694 - binary_crossentropy: 14.9993 - loss: 31.9733

2024-04-30 20:50:31.178639: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:31.180121: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 906ms/step - binary_accuracy: 0.0699 - binary_crossentropy: 14.9916 - loss: 31.9310 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.5146
Epoch 25/100


2024-04-30 20:50:32.945131: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:32.945206: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:50:32.945235: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 850ms/step - binary_accuracy: 0.0709 - binary_crossentropy: 14.9746 - loss: 31.9418

2024-04-30 20:50:48.338997: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:48.340274: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 17s 957ms/step - binary_accuracy: 0.0713 - binary_crossentropy: 14.9682 - loss: 31.8998 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5000
Epoch 26/100


2024-04-30 20:50:50.108348: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:50:50.108435: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 803ms/step - binary_accuracy: 0.0737 - binary_crossentropy: 14.9304 - loss: 31.9804

2024-04-30 20:51:04.752034: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:04.753699: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 911ms/step - binary_accuracy: 0.0740 - binary_crossentropy: 14.9249 - loss: 31.9382 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5000
Epoch 27/100


2024-04-30 20:51:06.546268: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:06.546355: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 793ms/step - binary_accuracy: 0.0696 - binary_crossentropy: 14.9971 - loss: 31.9674

2024-04-30 20:51:21.005867: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:21.007287: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 899ms/step - binary_accuracy: 0.0702 - binary_crossentropy: 14.9865 - loss: 31.9247 - val_binary_accuracy: 0.0635 - val_binary_crossentropy: 15.0947 - val_loss: 31.5000
Epoch 28/100


2024-04-30 20:51:22.753448: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:22.753605: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 763ms/step - binary_accuracy: 0.0666 - binary_crossentropy: 15.0447 - loss: 31.9716

2024-04-30 20:51:36.690542: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:36.691972: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 15s 846ms/step - binary_accuracy: 0.0671 - binary_crossentropy: 15.0362 - loss: 31.9290 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.5293
Epoch 29/100


2024-04-30 20:51:38.061103: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:38.061179: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:51:38.061209: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 789ms/step - binary_accuracy: 0.0732 - binary_crossentropy: 14.9382 - loss: 31.9686

2024-04-30 20:51:52.441560: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:52.442963: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 895ms/step - binary_accuracy: 0.0737 - binary_crossentropy: 14.9307 - loss: 31.9268 - val_binary_accuracy: 0.0952 - val_binary_crossentropy: 14.5830 - val_loss: 31.5000
Epoch 30/100


2024-04-30 20:51:54.192528: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:51:54.192614: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:51:54.192645: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 764ms/step - binary_accuracy: 0.0763 - binary_crossentropy: 14.8881 - loss: 31.9388

2024-04-30 20:52:08.182038: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:52:08.183640: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_2]]


18/18 ━━━━━━━━━━━━━━━━━━━━ 16s 869ms/step - binary_accuracy: 0.0767 - binary_crossentropy: 14.8818 - loss: 31.8974 - val_binary_accuracy: 0.0794 - val_binary_crossentropy: 14.8389 - val_loss: 31.4854


2024-04-30 20:52:09.929863: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
2024-04-30 20:52:09.929935: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_6]]
2024-04-30 20:52:09.929964: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11500698178648149573


In [5]:
# Test model
converted_clothing_embeds = model.clothing_model(tf.keras.applications.mobilenet_v3.preprocess_input(
    np.array([img.resize((224, 224)) for img in clothing_images[:8]])
))
converted_clothing_embeds = tf.expand_dims(converted_clothing_embeds, axis=1)
print(converted_clothing_embeds)

converted_outfit_embeds = model.outfit_model(tf.keras.applications.mobilenet_v3.preprocess_input(
    np.array([img.resize((224, 224)) for img in full_body_images[:8]])
))
converted_outfit_embeds = tf.expand_dims(converted_outfit_embeds, axis=0)
print(converted_outfit_embeds)

distances = tf.math.sqrt(tf.math.reduce_sum(tf.math.square(converted_outfit_embeds - converted_clothing_embeds), axis=-1))
best_samples = tf.math.top_k(distances, k=5).indices

best_samples

tf.Tensor(
[[[0. 0. 0. ... 1. 1. 0.]]

 [[0. 0. 0. ... 1. 1. 0.]]

 [[0. 0. 0. ... 1. 1. 0.]]

 ...

 [[0. 0. 0. ... 1. 1. 0.]]

 [[0. 0. 0. ... 1. 1. 0.]]

 [[0. 0. 0. ... 1. 1. 0.]]], shape=(8, 1, 512), dtype=float32)
tf.Tensor(
[[[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  ...
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]]], shape=(1, 8, 512), dtype=float32)


<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)>

In [6]:
full_body_filenames[7]

'jcrew_womens_tops-BV829-YD4884-fb.png'